### ISSUE TITLE
Not work with file:// protocol

### ISSUE THREAD

**Issue by unreal666** [vkiryukhin/vkthread#4]
> this.path = 'http'+ err.split('http')[1].split('vkthread.js').slice(0,-1) + 'worker.js';

It's code not work for url with file:// protocol.

**Comment by vkiryukhin** [comment]
Thank you for catching this bug. 
Not sure I will work on that right now as there is a way to set path explicitly with .setPath() function.  But in the future maybe I'll work on that.

**Comment by unreal666** [comment]
Can
    this.path = 'http'+ err.split('http')[1].split('vkthread.js').slice(0,-1) + 'worker.js';
replace with
    this.path = err.replace(/(?:(?!https?:|file:)[\w\W])*(.*?\/)vkthread\.js\b[\w\W]*/m, '$1') + 'worker.js';

**Comment by shivrajsa** [comment]
@vkiryukhin I am facing same issue. Not able to test on local env.
Could you please guide how can we test with dependent lib on local env without server.

Code example will be helpful
