### ISSUE TITLE
This doesn’t work with recursive functions.

### ISSUE THREAD

**Issue by ytrezq** [vkiryukhin/vkthread#7]
Json.stringify throw an error when the function calls`vkthread.exec`recursively :

    <script>
    var recursionLevel=0;
    var maxthreads=0;
    var recursion = function(obj){
      for(var b in obj) { 
        if(typeof obj.hasOwnProperty !== 'undefined' && obj.hasOwnProperty(b)){
          if(typeof obj[b] === "string" && obj[b].indexOf("domains.google") == -1 && obj[b].indexOf("googrz.co.nz")>-1){
	    alert(obj);
            obj[b] = obj[b].replace("googrz.co.nz", "googrz.co.in");
          }else if(typeof obj[b] === "object" && obj[b] && recursionLevel<150){ // call as an object "recursively"
            recursionLevel++;
            if(maxthreads<8) {
               maxthreads++;
               vkthread.exec(recursion,[obj[b]],function(data){maxthreads--;})
             } else
               recursion(obj[b]);
            recursionLevel--;
          }
        }
      }
    }
    recursion(window);
    </script>

**Comment by vkiryukhin** [comment]
JSON.stringify is javascript native function, which is used internally in vkthread.js 
Probable you get error something like  "cyclic object", which mean you pass an object which refers to itself directly or indirectly. I don't think it can be fixed within vkthread plugin; it is application level issue.

**Comment by ytrezq** [comment]
@vkiryukhin : which is why I think vkthread should be redisgned to not use`JSON.stringify`. I should definitely be able to use vkthread for recursive functions.

**Comment by vkiryukhin** [comment]
It's open source project. Clone it and do whatever you want.

**Comment by patrickfrank1** [comment]
To stringify cyclic objects you could use something like 'JSON.decycle()' and 'JSON.retrocycle()' form [this repo](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js)...
