### ISSUE TITLE
Integrate the plugin

### ISSUE THREAD

**Issue by m1m6** [vkiryukhin/vkthread#8]
Hi , i need to ask you 
how i can integrate it with my project 

i added the package file (vkThread) but when i attempt to execute any method , it show me an exception 
that Promise isn't defined!

**Comment by vkiryukhin** [comment]
Hi,
the latest version vkThread uses native ES6 Promise object. IE doesn't support it yet. I plan to work on cross-browser improvement within next few days: either bring back callback feature or add ES6 Promise library. Meanwhile, you can use version 0.5.7 if you want

**Comment by m1m6** [comment]
Hey, thanks for your response.

I integrate the version 0.5.7 with my project, but i'm using GWT, so when i tried to pass a javascript method to the VKthread, the console showed me a null value!!
does this mean that the javascript method doesn't passed to vkThread? 

here's my code: 
`
static native String flipName(String a) /*-{

		// ...implemented with JavaScript
		alert("jSCalled" + a);

	}-*/;
`
`	

               native String Excec() /*-{

		$wnd.vkthread.exec(flipName, //function to execute in a threads
		[], //arguments for the function
		function(data) { //collback function to process result
			var foo = data;
			console.log(foo);
		});

	}-*/;` 


console.log(foo); this line print NULL,!

**Comment by vkiryukhin** [comment]
1. your function doesn't have return statement, so it returns null;  callback function doesn't have data to display.
2. alert( ) in a thread doesn't make sense.

to test try something like 
```
function foo( ) {
    return 'Hello World!';
}
```
However, I'm not familiar with GWT, so can't help you with anything related to it, sorry.
